# Generated by Django 5.2.3 on 2025-07-03 17:55

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=2)),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=30)),
                ('escolaridade', models.CharField(choices=[('fun', 'Fundamental'), ('med', 'Médio'), ('sup', 'Superior'), ('pos', 'Pós-graduação'), ('mes', 'Mestrado'), ('dou', 'Doutorado')], max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/alunos', variations={'medium': (300, 300), 'thumb': (150, 150)})),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cursos.curso')),
            ],
        ),
    ]
