# Generated by Django 5.1.7 on 2025-05-21 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_aluno_escolaridade_alter_aluno_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.curso'),
        ),
    ]
