# Generated by Django 5.2.3 on 2025-07-02 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_aluno_ativo'),
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='academico.aluno')),
                ('disciplinas', models.ManyToManyField(to='disciplinas.disciplina')),
            ],
        ),
    ]
